def test_create_200m_project(index_page, main_page, create_project_page):
    index_page.login_flow()
    main_page.click_on_btn_start_new_project()
    create_project_page.input_project_name()
    create_project_page.choose_data_package()
    create_project_page.btn_next()
    create_project_page.btn_start_build_project()
    create_project_page.click_layer_thikness()
    create_project_page.input_layer_name()
    create_project_page.click_top_layer_dropdown()
